"""added_telegram_id

Revision ID: c6b9e14194b2
Revises: 2147c7a7d500
Create Date: 2022-07-18 17:46:35.536502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b9e14194b2'
down_revision = '2147c7a7d500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
