"""users_api_tokens

Revision ID: 44d236370883
Revises: c58b92780985
Create Date: 2022-07-18 17:20:10.052452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d236370883'
down_revision = 'c58b92780985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_token')
    # ### end Alembic commands ###
