"""users_api_tokens_remove_default

Revision ID: 2147c7a7d500
Revises: 44d236370883
Create Date: 2022-07-18 17:30:18.058256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2147c7a7d500'
down_revision = '44d236370883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
